"""Create a named tuple with the dic's names."""

from typing import NamedTuple, Any, Final

from . import get_lines_names as gl

type dic_lines = list[NamedTuple]


def get_namedtuple(lines: dic_lines, group: str) -> Any:
    the_names = gl.get_names(lines, group=group)
    specs = get_namedtuple_fields(names=the_names, group=group)
    DicNamedTuple = NamedTuple(group, specs["fields"])  # type: ignore
    dic_named_tuple = DicNamedTuple(*specs["values"])
    return dic_named_tuple


def get_namedtuple_fields(names: tuple[str, ...], group: str) -> dict[str, Any]:
    NAME: Final[str] = "name"

    the_values: list[str] = list(names)
    if NAME in the_values:
        msg: str = f"The field name '{NAME}' is reserved and must not be used."
        raise KeyError(msg)

    the_names: list[str] = list(names)

    the_names.insert(0, NAME)
    the_values.insert(0, group)
    assert len(the_names) == len(the_values)

    dtypes = [str] * len(the_names)

    # NOTE: If there are are duplicated names, they will be removed here and an error will be generated by the next line of code.
    fields = dict(zip(the_names, dtypes)).items()
    dupl_nb: int = len(the_names) - len(fields)
    if dupl_nb:
        msg = f"There are {dupl_nb} duplicated names in the group '{group}'."
        raise KeyError(msg)

    out = {"names": the_names, "values": the_values, "fields": fields}

    return out
