"""Create a named tuple with the dic's names."""

from __future__ import annotations  # Must be at the top
from typing import TYPE_CHECKING, NamedTuple, Any, Final

if TYPE_CHECKING:
    from .dic import IDic  # Only imported when checking types


def get_namedtuple(inst: IDic, group: str) -> Any:
    specs = get_namedtuple_fields(inst, group)
    DicNamedTuple = NamedTuple(group, specs["fields"])  # type: ignore
    dic_named_tuple = DicNamedTuple(*specs["values"])
    # print("named tuple:\n", nt)
    return dic_named_tuple


def get_namedtuple_fields(inst: IDic, group: str) -> dict[str, Any]:
    NAME: Final[str] = "name"

    lines = inst.get_lines_by_group(group=group)
    values = [line.name for line in lines]  # type: ignore
    if NAME in values:
        msg: str = f"The field name '{NAME}' is reserved and must not be used."
        raise KeyError(msg)

    names = values.copy()

    names.insert(0, NAME)
    values.insert(0, group)
    assert len(names) == len(values)

    dtypes = [str] * len(names)

    # NOTE: If there are are duplicated names, they will be removed here and an error will be generated by the next line of code.
    fields = dict(zip(names, dtypes)).items()

    check: int = len(names) - len(fields)
    if check:
        msg = f"There are {check} duplicated names in '{group}'."
        raise KeyError(msg)

    out = {"names": names, "values": values, "fields": fields}

    return out
