from collections.abc import KeysView
from typing import NamedTuple, Any

from .enums import DiczVar as vars


def main(group_nm: str, line_keys: KeysView) -> NamedTuple:
    the_names = tuple(line_keys)
    specs = get_fields(group_nm=group_nm, names=the_names)
    NamesTuple = NamedTuple(group_nm, specs["fields"])  # type: ignore
    names_tupl = NamesTuple(*specs["values"])
    return names_tupl


def get_fields(group_nm: str, names: tuple[str, ...]) -> dict[str, Any]:
    the_values: list[str] = list(names)
    if vars.GROUP in the_values:
        msg: str = f"The field name '{vars.GROUP}' is reserved and must not be used."
        raise KeyError(msg)

    the_names: list[str] = list(names)

    the_names.insert(0, vars.GROUP)
    the_values.insert(0, group_nm)
    assert len(the_names) == len(the_values)

    dtypes = [str] * len(the_names)

    # NOTE: If there are are duplicated names, they will be removed here and an error will be generated by the next line of code.
    fields = dict(zip(the_names, dtypes)).items()
    dupl_nb: int = len(the_names) - len(fields)
    if dupl_nb:
        msg = f"There are {dupl_nb} duplicated names '{group_nm}'."
        raise KeyError(msg)

    out = {"names": the_names, "values": the_values, "fields": fields}

    return out
